list all topics on main page
Zakkiassi/fe-nc-news pull request #1
Opened 2022-09-27 10:11 UTC by Zakkiassi

2022-09-27 10:28 UTC, leekli requested changes
Hey Zak,

Well done for getting the topics to load. The first coding ticket task is to display all the articles which this does not do yet just.

Please can you go back to this one and implement 'displaying all articles' (ticket 4) and then re submit your pull request once complete.

2022-09-28 10:56 UTC, yangalexyangg requested changes
Read the comments I have made so you can see what needs changing.
Also I have noticed that you have combined tickets 4, 5, and 6 which means there is a lot of additional requirements in this PR.

First of all I have noticed:
There are no links to home or single articles, only topics
There is not much responsive design
You do not have handling for non-existent ids for your individual article component. A simple 404 message is enough.

2022-09-28 10:56 UTC, yangalexyangg commented on src/App.js
> +        <Route path="/" element={<Topics />} />
You have "<Topics>" has your home path of '/' but there is no link to view all articles in this component so I can't see all of your articles like it mentions in the ticket

2022-09-28 10:56 UTC, yangalexyangg commented on src/components/Topic.jsx
> +    const {}
What is this doing?

2022-09-28 10:56 UTC, yangalexyangg commented on src/components/Articles.jsx
> +          //console.log(article);
remove comment

2022-09-28 10:56 UTC, yangalexyangg commented on src/components/Articles.jsx
> +  console.log(topic);
remove console.log

2022-09-28 10:56 UTC, yangalexyangg commented on src/components/Article.jsx
> +  console.log(article);
remove console.log pls

2022-09-28 10:56 UTC, yangalexyangg commented on src/components/Article.jsx
> +const Article = () => {
I see you have made a single Article component but there is no link to view a single article

2022-09-28 13:34 UTC, leekli requested changes
Hi Zak, thanks for making the changes, well done so far I can see some functionality working here however it's not quite there, see my feedback and suggested changes below. You will need to submit a new pull request once these are done:

- On the page(s) which display all the articles, or display articles by topic: You don't need the body of the article there, it just needs be a short summary of info on each article. The user doesn't need to see the body of the article unless they specifically click on that article. I would recommend you just display things like: article title, article author, maybe the topic name it belongs to? maybe a comment count and vote count? It's up to you really but I would remove the article body when its listing all articles or all articles by topic.
- When I go into all articles ... I can no longer see the topics, I have to click back. A user using React shouldn't need to press the back button. I can see the topics load on your home page only. Maybe it's worth having a NavBar which renders on every page, and the user can click things such as 'Home' which takes them back to the route "/", other options such as 'all articles' or 'topics' where it takes them to a page showing the topics or just back to the home page... again it's entirely up to you, but currently it is not easy or obvious to me as a user how I go back to a list of topics without clicking back
- I can see your single articles by id pages load which is great... I would recommend putting more info on this page, basically you could add everything that is returned from the api call on the object such as author, date, comment count, vote count and so on.
- If I manually type in an article id which does not exist in the address bar (e.g. /articles/9999) it takes me to an almost blank page, implement some error handling logic so the user gets a simple 404 error message page if they put in an article_id which does not exist.

Hope that helps, there's alot of feedback there but it's because there are 3 tickets in 1 pull request I'm afraid.

2022-09-29 14:49 UTC, leekli approved these changes
Brilliant Zak, well done for sorting all these changes. I can see it now functions as I would expect it to as a user.

Please feel free to merge this branch.

A note for your next branch that you create and pull request - make sure you remove all future console logs as there's still a few in your code. You don't need do this now, please merge this branch, then sort the console logs separately on a new branch when you begin ticket 7 :)

2022-09-29 14:58 UTC, merged